# github 에 올리면 안됩니다. 또는 secret 을 이용해야합니다.
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dev
  name: template-configmap
data:
  # 숫자에서 에러 발생: cannot convert int64 to string
  MYSQL_HOST: "mysql-ip"
  REDIS_HOST: "redis-ip"
  REDIS_PORT: "6379"
  ACCESS_SECRET: "SECRET"
  REFRESH_SECRET: "SECRET"

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: dev
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      namespace: dev
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: redis-ip  # Service 명 설정.
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: dev
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      namespace: dev
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "template"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: mysql-ip  # Service 명 설정.
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: dev
  name: template
  labels:
    app: template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template
  template:
    metadata:
      namespace: dev
      labels:
        app: template
    spec:
      containers:
        - name: template
          image: gksrlfw/template:0.0.2
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "dev"
            - name: NODE_ENV
              value: "development"
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: template-configmap
                  key: MYSQL_HOST
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: template-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: template-configmap
                  key: REDIS_PORT
            - name: ACCESS_SECRET
              valueFrom:
                configMapKeyRef:
                  name: template-configmap
                  key: ACCESS_SECRET
            - name: REFRESH_SECRET
              valueFrom:
                configMapKeyRef:
                  name: template-configmap
                  key: REFRESH_SECRET
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: template-nodeport
spec:
  type: NodePort
  selector:
    app: template
  ports:
    - port: 3000        # 서비스가 사용할 포트
      targetPort: 3000  # 서비스가 포워드할 컨테이너 포트
      nodePort: 30008   # 서비스의 노드포트

