apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: mysql-ip  # Service 명 설정.
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
