apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: redis-ip  # Service 명 설정.
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
