kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: dev
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      namespace: dev
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "template"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
