apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: template-nodeport
spec:
  type: NodePort
  selector:
    app: template
  ports:
    - port: 3000        # 서비스가 사용할 포트
      targetPort: 3000  # 서비스가 포워드할 컨테이너 포트
      nodePort: 30007   # 서비스의 노드포트
